apiVersion: v2
name: springboot-service
description: A Helm chart for Kubernetes

type: application

version: 0.2.0

appVersion: "0.2.0"

dependencies:
- name: outbox-service
  version: "0.2.0"
  repository: "https://tapiasmoreno.github.io/helm-charts"