apiVersion: v2
name: springboot-service
description: A Helm chart for Kubernetes

type: application

version: 1.1.1

appVersion: "1.1.1"

dependencies:
- name: outbox-service
  version: "0.3.0"
  repository: "https://tapiasmoreno.github.io/helm-charts"
  alias: outbox
  condition: outbox.enabled